import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import storesRouter from "./stores";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import usersRouter from "./users";
import walletRouter from "./wallet";
import couponsRouter from "./coupons";
import reviewsRouter from "./reviews";
import favoritesRouter from "./favorites";
import notificationsRouter from "./notifications";
import flashSalesRouter from "./flash-sales";
import driversRouter from "./drivers";
import analyticsRouter from "./analytics";
import adminRouter from "./admin";
import { faqRouter } from "./faq";
import { blogRouter } from "./blog";
import { contactRouter } from "./contact";
import { siteSettingsRouter } from "./site-settings";
import { uploadRouter } from "./upload";
import { inventoryAdminRouter } from "./inventory-admin";
import { flashSalesAdminRouter } from "./flash-sales-admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(storesRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(usersRouter);
router.use(walletRouter);
router.use(couponsRouter);
router.use(reviewsRouter);
router.use(favoritesRouter);
router.use(notificationsRouter);
router.use(flashSalesRouter);
router.use(driversRouter);
router.use(analyticsRouter);
router.use(adminRouter);
router.use(faqRouter);
router.use(blogRouter);
router.use(contactRouter);
router.use(siteSettingsRouter);
router.use(uploadRouter);
router.use(inventoryAdminRouter);
router.use(flashSalesAdminRouter);

export default router;
